server:
  port: 8082
  servlet:
    context-path: /cheeseKing
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/javawebproject?user=root&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC